local bufnr = vim.api.nvim_get_current_buf()
local kulala = require('kulala')
vim.keymap.set("n", "<leader>i", function()
  kulala.inspect()
end, { buffer = bufnr })
vim.keymap.set("n", "<leader>r", function()
  kulala.run()
end, { buffer = bufnr, nowait = true })
vim.keymap.set("n", "<leader>a", function()
  kulala.run_all()
end, { buffer = bufnr, nowait = true })
vim.keymap.set("n", "<leader>t", function()
  kulala.toggle_view()
end, { buffer = bufnr, nowait = true })
vim.keymap.set("n", "<leader>e", function()
  kulala.set_selected_env()
end, { buffer = bufnr, nowait = true })
vim.keymap.set("n", "<leader>c", function()
  kulala.copy()
end, { buffer = bufnr, nowait = true })
vim.keymap.set("n", "<leader>p", function()
  kulala.from_curl()
end, { buffer = bufnr, nowait = true })
vim.keymap.set("n", "[[", function()
  kulala.jump_prev()
end, { buffer = bufnr, nowait = true })
vim.keymap.set("n", "]]", function()
  kulala.jump_next()
end, { buffer = bufnr, nowait = true })
