local bufnr = vim.api.nvim_get_current_buf()
local kulala = require('kulala')
vim.keymap.set("n", "<leader>i", kulala.inspect, { buffer = bufnr })
vim.keymap.set("n", "<leader>r", kulala.run, { buffer = bufnr, nowait = true })
vim.keymap.set("n", "<leader>a", kulala.run_all, { buffer = bufnr, nowait = true })
vim.keymap.set("n", "<leader>t", kulala.toggle_view, { buffer = bufnr, nowait = true })
vim.keymap.set("n", "<leader>e", kulala.set_selected_env, { buffer = bufnr, nowait = true })
vim.keymap.set("n", "<leader>c", kulala.copy, { buffer = bufnr, nowait = true })
vim.keymap.set("n", "<leader>p", kulala.from_curl, { buffer = bufnr, nowait = true })
vim.keymap.set("n", "[[", kulala.jump_prev, { buffer = bufnr, nowait = true })
vim.keymap.set("n", "]]", kulala.jump_next, { buffer = bufnr, nowait = true })
